#!/usr/bin/env node
// ai/prompts/*.md is the single source of truth for every AI prompt.
// Edge Functions are deployed as self-contained bundles, so this script embeds
// the prompts into supabase/functions/_shared/prompts.generated.ts.
//   node scripts/sync_prompts.mjs          (write)
//   node scripts/sync_prompts.mjs --check  (CI: fail if out of date)
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'ai', 'prompts');
const out = join(root, 'supabase', 'functions', '_shared', 'prompts.generated.ts');

const entries = readdirSync(dir).filter((f) => f.endsWith('.md')).sort().map((f) => {
  const key = f.replace(/\.md$/, '').replace(/_([a-z])/g, (_, c) => c.toUpperCase());
  return `  ${key}: ${JSON.stringify(readFileSync(join(dir, f), 'utf8'))},`;
});
const content = `// GENERATED by scripts/sync_prompts.mjs from ai/prompts/*.md — do not edit by hand.\n` +
  `export const PROMPTS = {\n${entries.join('\n')}\n} as const;\n`;

if (process.argv.includes('--check')) {
  if (!existsSync(out) || readFileSync(out, 'utf8') !== content) {
    console.error('prompts.generated.ts is out of date. Run: node scripts/sync_prompts.mjs');
    process.exit(1);
  }
  console.log('prompts up to date');
} else {
  writeFileSync(out, content);
  console.log(`wrote ${out}`);
}
